---
Gemfile:
  required:
  - gem: rake
  - gem: rspec-puppet
    version: '~> 2.0'
  - gem: puppetlabs_spec_helper
    version: '>= 0.8.0'
  - gem: puppet-lint
    version: '>= 1'
  - gem: simplecov
  - gem: puppet-blacksmith
    version: '>= 3.1.0'
    options:
      groups:
      - 'development'
  - gem: rest-client
    version: '< 1.7'
    options:
      platforms:
      - 'ruby_18'
      groups:
      - 'development'
  - gem: mime-types
    version: '~> 1.0'
    options:
      platforms:
      - 'ruby_18'
      groups:
      - 'development'
.puppet-lint.rc:
  default_disabled_lint_checks:
  - '80chars'
  - 'class_inherits_from_params_class'
spec/spec_helper.rb:
  requires: []
